services:
  backend:
    build: ./backend
    container_name: ecommerce-backend
    ports:
      - "5000:5000"

  frontend:
    image: httpd:latest
    container_name: ecommerce-frontend
    volumes:
      - "./frontend:/usr/local/apache2/htdocs"
    ports:
      - "3000:80"
    depends_on:
      - backend